# Generated by Django 2.2.5 on 2020-08-25 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(blank=True, default='', max_length=100)),
                ('game_designer', models.CharField(blank=True, default='', max_length=100)),
                ('game_publisher', models.CharField(blank=True, default='', max_length=100)),
                ('game_min_player', models.IntegerField(blank=True, default=1)),
                ('game_max_player', models.IntegerField(blank=True, default=1)),
                ('game_image_path', models.CharField(blank=True, default='', max_length=1000)),
                ('game_playtime', models.CharField(blank=True, default='', max_length=100)),
                ('game_expansion', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_fname', models.CharField(default='', max_length=100)),
                ('player_lname', models.CharField(default='', max_length=100)),
                ('player_wins', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(default='', max_length=100)),
                ('session_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_session', to='BoardGame.Game')),
                ('session_player', models.ManyToManyField(related_name='player_session', to='BoardGame.Player')),
                ('session_winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_winner', to='BoardGame.Player')),
            ],
        ),
    ]
